### ISSUE TITLE
A taxonomy of terms

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#44]
A taxonomy of terms shall be built to classify the different operations performed in the context of TDataFrame based processing.
Examples of these terms are Lazy Action, Instant Action, Transformation, Filter.
All this should appear in a very clear way in the Doxygen documentation pf the classes.

**Comment by eguiraud** [comment]
A very early-drafty version of the user guide is available [here](https://gist.github.com/bluehood/c05a97085e47f71505297b3786337475).
It might be useful to have feedback on the terminology used there already at this time.

**Comment by Axel-Naumann** [comment]
Nice! A few comments:

- you should not pass a num-core argument to `ROOT::EnableImplicitMT(4);` (I *knew* people would do this which is why I was arguing against having this parameter to begin with, but I lost and now we have to pay :-)

- maybe write `d.Histo("pt")->Draw()`?

- "users are responsible for the thread-safety of this lambda when executing with implicit multi-threading enabled" - isn't that true for all lambdas passed to any TDataFrame interface?

**Comment by eguiraud** [comment]
Thanks for taking a look at it

- not sure I understand: do you mean I should not encourage the passing of that argument (because it's better and safer to let TBB decide the number of workers)?
- I'll put in in a comment (`//alternatively: ...`)
- weeeeell technically yes, but filters and temporary branch expressions will be pure functions most of the time. but you are right, I will point out that filters/tmp branches with side-effects also have to be thread-safe

**Comment by Axel-Naumann** [comment]
On point 1: Indeed. The doc says "If not specified or set to zero, the number of threads is automatically decided by the implementation." Doxygen doesn't clearly show that there is a default argument: https://root.cern.ch/doc/v608/namespaceROOT.html#ade6e397b327482d267ad54de92db4b89 - but we (the ROOT team) agreed there should be one, and that people should "basically never specify the numcore parameter". So for you: yes, please remove the "4".

**Comment by eguiraud** [comment]
done :)

**Comment by eguiraud** [comment]
terms that I tried to use consistently while writing the guide are in italic (pr #59):

- _transformations_: filtering and adding a _temporary branch_
- _named filters_: filters with a name
- _actions_: they can be _instant_ or _lazy_ according to when they trigger
- _branch list_: a [initializer, std] list of strings representing branch names
- _call chain_ and _call graph_: the second is a generalization of the first
- _temporary branches_
- _ranges_ and _ranged actions_

I used _entry_ and _event_ interchangeably.
