### ISSUE TITLE
Allow to start from an empty TDataFrame

### ISSUE THREAD

**Issue by dpiparo** [bluehood/tdataframe#56]
It would be nice to allow for an empty TDataFrame which could allow looping for N entries (`auto myDf = ROOT::TDataFrame(myNumberOfEntries)`).
This could immediately allow to run workflow such as toy experiments generation and Monte Carlo events generation and creation of histograms (or whatever via `Foreach`).
When the `Checkpoint`/`Tee` functionality is available, this new way of steering calculations will allow to create ROOT files.
De facto, TDataFrame would become a veritable "mini parallel data processing framework".

At the level of implementation, the aforementioned feature cannot be achieved with `TTreeProcessor` but rather with `TThreadExecutor`: the `TDataFrameImpl::Run` function could accommodate this change.

**Comment by eguiraud** [comment]
Nice concept :)
How would you tell the `TDataFrame` how to generate the entries? At high level I can prospect something like
```c++
ROOT::TDataFrame d(generator, nEntries);
auto h = d.Histo;
```
where generator represents/implements the Monte Carlo or whatever mechanism for the creation of events.

**Comment by dpiparo** [comment]
Hi,

pretty much like it!
Perhaps we can be even more minimalistic, relying on the AddBranch method rather than specifying the generator right away: 
`
ROOT::TDataFrame d(nEntries);
d.AddBranch("myProduct",myGenerator, myBranchList);
[...]
auto h1 = d.Histo("electrons_pt");
auto h1 = d.Histo("electrons_eta");
[...]
`

**Comment by eguiraud** [comment]
Wow, so...most of the building blocks are already there. This works (and can be made less awkward):

```c++
/***** BOILERPLATE ******/
#include "TDataFrame.hxx"
#include "TFile.h"
#include "TTree.h"
#include <atomic>
#include <iostream>

int main() {
{
   TFile wf("emptyTree.root", "RECREATE");
   TTree t("emptyTree", "emptyTree");
   int a;
   t.Branch("a", &a);
   t.Fill();
   t.Fill();
   t.Fill();
   t.Write();
}

   TFile f("emptyTree.root");
/***** END OF BOILERPLATE ******/

   ROOT::TDataFrame d("emptyTree", &f);
   unsigned int entry(0);
   d.AddBranch("foo", [&entry]() { return entry*entry; })
    .Filter([](int foo) { std::cout << foo << std::endl; return true; }, {"foo"})
    .Foreach([&entry]() { ++entry; });

   return 0;
}
```

The multi-threaded case would read even more awkwardly, but it should work as well.

**Comment by dpiparo** [comment]
Hi,

this would be exactly the functionality and we do have almost all of the building blocks available already. Perhaps using `TThreadExecutor` we can get rid of the awkward creation of an empty tree, get parallelism "for free", and use the rest as is...

**Comment by eguiraud** [comment]
I'll have to think about that :) I think there are two distinct use-cases here though, correct me if I'm wrong:

1. running a Monte Carlo simulation to produce the events, instead of reading pre-stored events from file. The difference in usage in these two cases should be almost non-existent, as TDataFrame aims to abstract users from "where the data comes from". One could imagine to construct the data-frame object from some sort of Monte Carlo object and then work as usual.
2. constructing an empty data-frame and "manually" adding branches with `AddBranch`. as we saw this is already possible by passing a dummy tree with the desired number of entries and never reading its branches. of course this method is awkward but I think it would not be too complicated to just let users build a `TDataFrame(numberOfEntries)` like you proposed in your original post, it's just a matter of adding that constructor and, in that case, run a `for(i in range(numberOfEntries))` loop rather than a `while(reader.Next())` loop. parallelism falls out automatically in this case.

**Comment by eguiraud** [comment]
done in ROOT
